import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import BotMsg from '../components/botMsg';
import TextBox from '@/components/TextBox';
import React, { useState } from 'react';

const inter = Inter({ subsets: ['latin'] });

function Home() {

  const [textInput, setText] = useState('');

  const handleTextChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setText(event.target.value);
  };

  const [userMsg, setUserMsg] = useState('');

  const [output, setOutput] = useState('');

  const [value, setValue] = useState<string>('');

  const [prompt, setPrompt] = useState<string>('');

  const [completion, setCompletion] = useState<string>('');

  const handleInput = React.useCallback(
    (e: React.ChangeEvent<HTMLInputElement>) => {
      setValue(e.target.value);
    },
    []
  );

  const handleButtonClick = async () => {
    {/*const response = await fetch('/api/my-api');
    const data = await response.json();
  setOutput(data.output);*/}
    setUserMsg(textInput);
  };

    const handleKeyDown = React.useCallback(
      async (e: React.KeyboardEvent<HTMLInputElement>) => {
        if (e.key === 'Enter') {
          setPrompt(value);
          setUserMsg(value);
          setCompletion('Loading...');
          const response = await fetch('/api/hello', {
            method: 'POST',
            headers: {
              'Content-Type': 'application/json',
            },
            body: JSON.stringify({ text: value }),
          });
          const data = await response.json();
          setValue('');
          setCompletion(data.result.choices[0].text);
        }
      },
      [value]
    );

  return (
    <>
      <Head>
        <title>DOT Bot</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/flightChat.png" />
      </Head>

      <div className="flex justify-center items-center from-blue-300 to-slate-500 w-screen h-screen bg-gradient-to-br">
        <div className="flex flex-col justify-between min-w-[65vw] min-h-[70vh] bg-white rounded-xl shadow-lg">
          <div className="m-2 p-6 max-w-xl w-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
            <div className="shrink-0">
              <img className="w-16" src="/flightChat.png" />
            </div>
            <div>
              <div className="text-xl font-medium text-black">DOT Bot</div>
              <p className="text-slate-500">
               {completion.split('\n').map(item => <>{item}<br/></>)}
              </p>
            </div>
          </div>
          <div className="self-end m-2 p-6 max-w-xl min-w-[400px] w-auto bg-white rounded-xl shadow-lg flex items-center space-x-4">
            <div>
              <div className="text-xl font-medium text-black">User</div>
              <p className="text-slate-500">{userMsg}</p>
            </div>
          </div>

          <div className="flex relative justify-between items-center mx-[2vw] bottom-2 min-w-[60vw] min-h-[9vh] max-h-[15vh] border-slate-500 border-[0.5px] rounded-xl space-x-2">
            <div>
              <input
                className="relative w-[50vw] left-1 outline-none"
                type="text"
                value={value}
                onChange={handleInput}
                onKeyDown={handleKeyDown}
              />
            </div>
          </div>
        </div>
      </div>
    </>
  );
};
export var textInput: any;
export default Home;

